//
// Created by tony on 28/09/2026.
//

#pragma once

#include <type_traits>
#include <limits>

namespace dagbase
{
    //! Zigzag encoding of a signed integral type to the corresponding unsigned integer type.
    //! This is useful in variable-length integer encoding to avoid large encoded values for small negative integers.
    //! \note Generated by AI and modified for style.
    template <typename T, std::enable_if_t<std::is_integral_v<T> && std::is_signed_v<T>, int> = 0>
    constexpr std::make_unsigned_t<T> zigzagEncode(T n)
    {
        using U = std::make_unsigned_t<T>;
        constexpr int shift = std::numeric_limits<T>::digits;  // bits - 1
        return static_cast<U>((static_cast<U>(n) << 1) ^ static_cast<U>(n >> shift));
    }

    //! Zigzag decoding for an unsigned integral type to the corersponding signed integer type
    //! This is useful for variable-length integer decoding to avoid large encoded values for small negative integers.
    //! \note Generated by AI and modified for style.
    template <typename U, std::enable_if_t<std::is_integral_v<U> && std::is_unsigned_v<U>, int> = 0>
    constexpr std::make_signed_t<U> zigzagDecode(U n)
    {
        using S = std::make_signed_t<U>;
        return static_cast<S>((n >> 1) ^ static_cast<U>(-(n & 1)));
    }
}